---
title: "CV"
author: "Thomas Van Hoey 司馬智"
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  pdf_document:
    latex_engine: xelatex
    template: template_thomas.tex
CJKmainfont: Noto Sans CJK TC
sansfont: Impact
mainfont: Noto Serif

geometry: margin=1in


jobtitle: "Ph.D candidate Linguistics"
affiliation: "National Taiwan University"
address: "N. 16-3, Siyuan St., Chungcheng District, 100 Taipei"
#addressuni: "Taipei, 106, Da'an district, Roosevelt Rd., Sect. 4, n. 1"
fontawesome: yes
academicons: yes

email: d04142001@ntu.edu.tw
email2: thomas_van_hoey@outlook.com
github: github.com/simazhi
phone: "+886-(0)-909 345 062"
web: thomasvanhoey.com
orcid: 0000-0002-5226-9752

updated: yes


keywords: R Markdown, academic CV, template

#fontfamily: mathpazo
#fontfamilyoptions: sc, osf
fontsize: 12pt
linkcolor: blue
urlcolor: blue
---

<!-- # Biography 

qulificiation,
outstanding teaching
reserch
community engagement
3 paragraphs of prose

-->
\thispagestyle{empty}
# Research interests:

Ideophones, onomatopoeia, mimetics; Cognitive Linguistics; lexical semantics; Cognitive Grammar;  
historical linguistics; Chinese (in all its variants)

# Education:

**PhD Linguistics**, National Taiwan University: Graduate Institute of Linguistics \hfill 2015-2019 (expected)  
Advisor: [Lu Chiarung 呂佳蓉, Ph.D](chiarung.blog.ntu.edu.tw) \hfill Taipei, Taiwan

**MA Linguistics** *magna cum laude*, University of Leuven \hfill 2014-2015  
Thesis: *A typological analysis of mimetic words in Middle Chinese (6th-12th cent.)*  \hfill Leuven, Belgium
Advisor: [Jean-Christophe Verstraete, Ph.D](https://perswww.kuleuven.be/~u0005010/jcv/) 

**MA Sinology** *magna cum laude*, University of Leuven \hfill 2013-2014  
Thesis: *The Guwen yundong 古文运动 (Classical Prose Movement)* \hfill Leuven, Belgium \newline
*during Tang and Song: Ideological as well as Stylistic Innovation?*  
Advisor: [Willy Vande Walle, Ph.D](https://www.kuleuven.be/wieiswie/en/person/00009507)

**Year-long Mandarin Chinese exchange study**, Suzhou University 苏州大学 \hfill 2012-2013 \newline
\mbox{} \hfill Suzhou, China

**BA Sinology** *cum laude*, University of Leuven \hfill 2009-2012 \newline
\mbox{} \hfill Leuven, Belgium

# Additional training and education
Summer school: Chinese Digital Humanities. Leiden: Leiden University. \hfill July 2016

Summer school:  Translating Chinese (Summer +10). Taipei: National Taiwan University. \hfill July 2014

# Honours and awards

*Financial Assistance Grant for International Students* 國際學位生助學金 \hfill 2018-2019

*Research Fellowship for Outstanding International Doctoral Students* 優秀國際博士生獎學金 \hfill 2015-2018

*Scholarship from the Hanban 汉办, for long-term study of Chinese* \hfill 2012-2013


# Research

<!-- ## Books -->

## Book chapters

**Van Hoey, Thomas** & Chiarung Lu. 2019. Lexical variation of ideophones in Chinese classics: Their implications in embodiment and migration. In Janice Fon (ed.), *Dimensions of diffusion and diversity*, 195–226. (Cognitive Linguistics Research 63). Berlin; Boston: De Gruyter Mouton.

## Refereed articles

**Van Hoey, Thomas**. 2018. Does the thunder roll? Mandarin Chinese meteorological expressions and their iconicity. *Cognitive Semantics* (4:2), 230-259.

<!-- ## Non-refereed articles -->

<!-- ## Journalism -->

## Resources

**Van Hoey, Thomas** & Arthur Lewis Thompson. 2019. Chinese ideophone database. doi: 10.17605/OSF.IO/KPWGF \hfill (in progress)

## Theses

PhD thesis Linguistics \hfill 2019 (expected)  
*Lexical variation and semantic change in literary Chinese ideophones: A cognitive and computational linguistic approach* 中文文言象聲詞的詞彙變異與語意變遷: 以認知與計算語言學方法探討 \hfill (proposed title)

MA thesis Linguistics (grade: 17.4/20)\hfill 2014-2015   
*Ideophones in Middle Chinese: A typological study of a Tang dynasty poetic corpus*

<!-- >Based on a corpus of Midde Chinese poetry, I identified a set of mimetic words in Middle Chinese. I worked on an analysis of their morphological, phonological, syntactic and semantic properties, against a typological background. -->

MA thesis Sinology (grade: 18.6/20)\hfill 2013-2014  
*The *Guwen yundong 古文运动 *(Classical Prose Movement) during Tang and Song: Ideological as well as Stylistic Innovation?*

<!-- >Using quantitative analyses (dendrograms, PCA, cluster analysis), I verified which authors were stylistically part of the Classical Prose Movement. This movement promoted an older style (used some four centuries or more earlier), condemning the formal style of the contemporary popular parallel prose. Unlike theoretical research hitherto suggested, my analysis shows that only a few authors formed the core of the movement. The presence of these authors fits nicely into the dominant framework of the emergence of Neo-Confucianism in the Song dynasty (10th-13th cent.). -->

<!-- ## Publications currently under review -->

## Publications currently being written

**Van Hoey, Thomas** & Chiarung Lu. The blending of bending: Worldbuilding in *Avatar: The Last Airbender* and *The Legend of Korra*.

**Van Hoey, Thomas** & Chiarung Lu. A semantic map for ideophones: From an implicational hierarchy to the spinning top model.

**Van Hoey, Thomas** & Arthur Lewis Thompson. Bridging phonology, meaning, and written form across time: Introducing a database of Chinese literary ideophones.


# Conferences

<!-- ## Keynote addresses -->

## Invited talks

**Van Hoey, Thomas**. 2017. Chinese ideophones in historical corpora: A case study of mental space markers. Workshop on Mimetics II: New approaches to old questions. Nagoya: Nanzan University. 11 November 2017. Funding: MOST-106-2922-I-002-596. https://www.nanzan-u.ac.jp/Menu/news/2017/pdf/171016_workshop.pdf

## Conference presentations (oral)

**Van Hoey, Thomas** & Chiarung Lu. 2019. Reduplication as a trigger of intersubjectivity: Mandarin Chinese ideophones and reduplication in the CHILDES corpora. Oral presentation presented at the ICLC 15 [International Cognitive Linguistics Conference], Nishinomiya: Kwansei Gakuin University. 6-11 August 2019. https://iclc2019.site/. 

**Van Hoey, Thomas**. 2019. Radiant suns, burning fires and brilliant flowers: The onomasiology and radical support of Chinese literary LIGHT ideophones. Oral presentation presented at the ICLC 15 [International Cognitive Linguistics Conference], Nishinomiya: Kwansei Gakuin University. 6-11 August 2019. https://iclc2019.site/.


**Van Hoey, Thomas** & Arthur Lewis Thompson. 2019. Reduplication as a trigger of intersubjectivity: Mandarin Chinese ideophones and reduplication in the CHILDES corpora. Oral presentation presented at the ILL 12 [International Symposium on Iconicity in Language and Literature], Lund: Lund University. 3-5 May 2019. https://konferens.ht.lu.se/en/ill-12/.


**Van Hoey, Thomas** & Chiarung Lu. 2018. All that glitters is not gold: Prototypical semantic change in shiny Literary Chinese ideophones. ICPEAL 17 [International Conference on the Processing of East Asian Languages]-CLDC 9 [Conference on Language, Discourse, and Cognition]. Taipei: National Taiwan University. 19-21 October 2018.  https://homepage.ntu.edu.tw/~gilntu/icpeal2018cldc/

**Van Hoey, Thomas**. 2016. Ideophones in Old Chinese: The case of the *Shijing* 詩經. ISACG [International Symposium on Ancient Chinese Grammar] 9. Berlin: Humboldt University. 29-30 July 2016.

**Van Hoey, Thomas**. 2016. A diachronic analysis of ideophones in Chinese. Summer school in Chinese Digital Humanities. Leiden: Leiden University. 6-9 July 2016.

**Van Hoey, Thomas** & Chiarung Lu. 2016. The distribution of ideophones in Tang poems: A variationist perspective. CLDC [Conference on Language, Discourse, and Cognition] 8. Taipei: National Taiwan University.13-14 May 2016. http://homepage.ntu.edu.tw/~gilntu/cldc/2016/

<!-- ## Conference panels -->

## Conference presentations (posters)

**Van Hoey, Thomas**. 2018. The blending of bending: Worldbuilding in *Avatar: The Last Airbender* and *The Legend of Korra*. RaAM [Association for Researching and Applying Metaphor] 12. Hong Kong: Hong Kong Polytechnic University. 27-30 June 2018. Funding: MOST-107-2922-I-002-237. http://www.engl.polyu.edu.hk/events/raam/

**Van Hoey, Thomas**. 2017. The thunder rolls: Iconicity and ideophones in Chinese meteorlogical expressions. CLS-MPI Iconicity Focus Group Workshop: Types of Iconicity in Language Use, Development and Processing. Nijmegen: Max Planck Institute for Psycholinguistics. 6-7 July 2017. Funding: NTU, College of Liberal Arts. http://iconicity.ruhosting.nl

**Van Hoey, Thomas**. 2016. Ideophones in Premodern Chinese: Revisiting Dingemanse’s implicational hierarchy (poster). Mimetics in Japanese and other languages in the world (日本語と世界諸言語のオノマトペ). Tachikawa: NINJAL. 17-18 December 2016. Funding: MOST-105-2922-I-002-682. https://pj.ninjal.ac.jp/mimetics/en/

## Departmental lectures

**Van Hoey, Thomas**. 2017. A semantic map for ideophones: From an implicational hierarchy to the spinning top model. Brown Bag Lectures. Taipei: National Taiwan University. 26 April 2017.

<!-- # Funding -->

<!-- # Teaching -->

<!-- # Supervision -->

<!-- # Examinations -->

<!-- # Consultancies 
Anno annotations? 安諾

Project van Daryl Sterk!
-->

<!-- # Media section -->

# Employment

Research Assistant, National Taiwan Normal University \hfill 2019  
*Assisting in Formosa-related newspaper project, for Dr. Ann Heylen*

Research and Teaching Assistant, National Taiwan University \hfill 2016-2019  
*Assisting in courses and research, for Dr. Chiarung Lu*

Teaching Assistant, English summer camp at Wesley Girls' High School (Taipei), \hfill 2018  
organized by the Language Training & Testing Center at National Taiwan University 

Research Assistant for the Formosan Spoken Corpus, National Taiwan University \hfill 2017-2018  
*Transcribing Isbukun Bunun, project of Dr. Li-May Sung*

Dutch translator of Chinese short stories, babel101.com \hfill 2014-2016

Freelance Chinese-Dutch translator and interpreter, Judicial Court of Leuven \hfill 2014-2016

Assistant, East-Asian Library (University of Leuven) \hfill 2014-2015

Freelance translator Dutch-Chinese, Expat Insurances \hfill 2012-2013

# Languages

**Active:** Dutch, English, Chinese, French 

**Passive:** Japanese, German, Premodern Chinese

**Basic knowledge:** Isbukun Bunun (Austronesian)

# Service 
<!-- Administration, leadership, management -->

## Conference organisation

ICPEAL 17 - CLDC 9 \hfill 2018  
*International Conference for the Processing of East Asian Languages* and *Conference on Language, Discourse, and Cognition*
http://homepage.ntu.edu.tw/~gilntu/icpeal2018cldc/

>Role: coordinator of the student committee responsible for organizing the joint conference

## Student representation
**Eoos** (student association for the research unit of Area Studies at KU Leuven, Belgium)

- Webmaster \hfill 2014-2015
- President & Webmaster \hfill 2013-2014
- Vice President Sinology \hfill 2011-2012
- Educational representative \hfill 2011-2012
- Chairman Student Council Faculty of Arts (StRaaL) \hfill 2011-2012

> Roles: membership of the following bodies: Permanent Educational Commission (POC) of Area Studies, Curriculum Commission (CC) of Linguistics, CC of Sinology, Didactical Commission, Faculty board of the Faculty of Arts, Faculty council of the Faculty of Arts, General student council (LOKO and STURA KU LEUVEN), Student council of the Faculty of Arts (StRaaL)

<!-- # Professional development
learning, seminar,
summer schools?
-->

# Technological knowledge
- Microsoft office (Word, Excel, PowerPoint, Access) and open source variants
- \LaTeX (typesetting)
- R, Python (statistical research)
- Experimental design and corpus research
- Regression analysis, cluster analysis, principal components analysis, dendrograms
- Knowledge of general linguistic theories, (lexical-semantial) Cognitive Linguistics, descriptive and typological linguistics, computational linguistics

# Relevant courses
* National Taiwan University: 

> Syntax, Phonology, Lexical Semantics, R Language and Data Science, Linguistic Fieldwork, Logical Analysis of Language, Language and Culture, Corpus Linguistics, Advanced Cognitive Grammar, Cognitive Science, Linguistics in Manga and Animation, Problem-Based Learning Appraoch to SLA

* University of Leuven: 

>Language Typology and Universalia, Computational Linguistics, Modern Mandarin Chinese and Classical Chinese (BA and MA courses), Lexicology and Morphology, Pragmatics and Discourse Analysis, Language Documentation and Description, Language Experiment, Historical Linguistics, Comparative Linguistics, Usage-based Linguistics 

# Other awards and certificates
- Intermediate level, Isbukun Bunun Proficiency Test  \hfill 2018
- 1st place at Hackathon Taiwanese Linguistics Olympiad \hfill 2017
- HSK 6 (Chinese Proficiency Test, level 6) \hfill 2013
- HSK 5 (Chinese Proficiency Test, level 5) \hfill 2013
- 3rd place, Chinese calligraphy competiton with hard pen for Belgian university students \hfill 2011
- HSK 3 (Chinese Proficiency Test, level 3) \hfill 2010
- Finalist, HUB (Brussels) Language Competition, French  \hfill 2009
-	Finalist, Olyfran (French language competition)  \hfill 2007

<!-- # Referees -->
<!-- Chiarung, Hsieh, Willy, Standaert, Carine -->

